"""Auditable provider mappings for the market data pipeline."""

from __future__ import annotations

from dataclasses import dataclass


PROVIDER_PRIORITIES = {
    "Derived": 5,
    "FRED": 10,
    "BOK ECOS": 10,
    "CoinGecko": 20,
    "Alpha Vantage": 30,
}


@dataclass(frozen=True)
class ProviderMapping:
    instrument_id: str
    provider: str
    provider_symbol: str
    expected_unit: str
    frequency: str
    source_url: str
    direct: bool
    value_type: str
    change_unit: str
    history_series_id: str | None = None
    priority: int = 100
    enabled: bool = True
    notes: str = ""
    attribution_notes: str = ""
    redistribution_review_required: bool = False
    stat_code: str | None = None
    item_code1: str | None = None
    cycle: str | None = None
    function: str | None = None
    from_symbol: str | None = None
    to_symbol: str | None = None
    symbol: str | None = None
    coingecko_id: str | None = None
    sanity_min: float | None = None
    sanity_max: float | None = None
    week_lag: int = 5


FRED_SERIES = {
    "fed_target_range": ProviderMapping(
        instrument_id="fed_target_range",
        provider="FRED",
        provider_symbol="DFF",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DFF",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="fed_target_range",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-2.0,
        sanity_max=30.0,
        notes="Effective Federal Funds Rate proxy for the policy-rate dashboard slot.",
    ),
    "ust2y": ProviderMapping(
        instrument_id="ust2y",
        provider="FRED",
        provider_symbol="DGS2",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DGS2",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="ust2y",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-5.0,
        sanity_max=30.0,
    ),
    "ust10y": ProviderMapping(
        instrument_id="ust10y",
        provider="FRED",
        provider_symbol="DGS10",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DGS10",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="ust10y",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-5.0,
        sanity_max=30.0,
    ),
    "ust30y": ProviderMapping(
        instrument_id="ust30y",
        provider="FRED",
        provider_symbol="DGS30",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DGS30",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="ust30y",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-5.0,
        sanity_max=30.0,
    ),
    "us10y_real_yield": ProviderMapping(
        instrument_id="us10y_real_yield",
        provider="FRED",
        provider_symbol="DFII10",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DFII10",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="us10y_real_yield",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-10.0,
        sanity_max=30.0,
    ),
    "us10y_breakeven": ProviderMapping(
        instrument_id="us10y_breakeven",
        provider="FRED",
        provider_symbol="T10YIE",
        expected_unit="%",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/T10YIE",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="us10y_breakeven",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-10.0,
        sanity_max=30.0,
    ),
    "wti": ProviderMapping(
        instrument_id="wti",
        provider="FRED",
        provider_symbol="DCOILWTICO",
        expected_unit="USD/bbl",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DCOILWTICO",
        direct=True,
        value_type="price",
        change_unit="%",
        history_series_id="wti",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-100.0,
        sanity_max=1000.0,
        notes="Allows negative WTI prints such as April 2020; rejects obvious malformed extremes.",
    ),
    "brent": ProviderMapping(
        instrument_id="brent",
        provider="FRED",
        provider_symbol="DCOILBRENTEU",
        expected_unit="USD/bbl",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/DCOILBRENTEU",
        direct=True,
        value_type="price",
        change_unit="%",
        history_series_id="brent",
        priority=PROVIDER_PRIORITIES["FRED"],
        sanity_min=-100.0,
        sanity_max=1000.0,
    ),
}


FRED_DISABLED_SERIES = {
    "gold": ProviderMapping(
        instrument_id="gold",
        provider="FRED",
        provider_symbol="GOLDAMGBD228NLBM",
        expected_unit="USD/oz",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/GOLDAMGBD228NLBM",
        direct=True,
        value_type="price",
        change_unit="%",
        history_series_id="gold",
        priority=PROVIDER_PRIORITIES["FRED"],
        enabled=False,
        sanity_min=0.0,
        sanity_max=100000.0,
        notes="Disabled because the IBA/LBMA daily gold price series was removed from FRED/API distribution in January 2022.",
    ),
    "vix": ProviderMapping(
        instrument_id="vix",
        provider="FRED",
        provider_symbol="VIXCLS",
        expected_unit="index",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/series/VIXCLS",
        direct=True,
        value_type="point_index",
        change_unit="points",
        history_series_id="vix",
        priority=PROVIDER_PRIORITIES["FRED"],
        enabled=False,
        sanity_min=0.0,
        sanity_max=250.0,
        notes="Disabled pending redistribution and attribution review for public GitHub Pages publication.",
        attribution_notes="Cboe copyrighted data surfaced through FRED; citation/terms review required before automatic redistribution.",
        redistribution_review_required=True,
    ),
    "copper": ProviderMapping(
        instrument_id="copper",
        provider="FRED",
        provider_symbol="PCOPPUSDM",
        expected_unit="USD/metric ton",
        frequency="monthly",
        source_url="https://fred.stlouisfed.org/series/PCOPPUSDM",
        direct=True,
        value_type="price",
        change_unit="%",
        history_series_id="copper",
        priority=PROVIDER_PRIORITIES["FRED"],
        enabled=False,
        sanity_min=0.0,
        sanity_max=100000.0,
        notes="Monthly IMF global copper price via FRED; disabled pending redistribution and attribution review. 1D/1W changes are not calculated.",
        attribution_notes="IMF copyrighted data surfaced through FRED; citation/terms review required before automatic redistribution.",
        redistribution_review_required=True,
    ),
}


BOK_SERIES = {
    "bok_base_rate": ProviderMapping(
        instrument_id="bok_base_rate",
        provider="BOK ECOS",
        provider_symbol="722Y001:0101000",
        expected_unit="%",
        frequency="daily",
        source_url="https://ecos.bok.or.kr/api/",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="bok_base_rate",
        priority=PROVIDER_PRIORITIES["BOK ECOS"],
        stat_code="722Y001",
        item_code1="0101000",
        cycle="D",
        sanity_min=-2.0,
        sanity_max=30.0,
        notes="Official ECOS base-rate series: 한국은행 기준금리.",
    ),
    "ktb3y": ProviderMapping(
        instrument_id="ktb3y",
        provider="BOK ECOS",
        provider_symbol="817Y002:010200000",
        expected_unit="%",
        frequency="daily",
        source_url="https://ecos.bok.or.kr/api/",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="ktb3y",
        priority=PROVIDER_PRIORITIES["BOK ECOS"],
        stat_code="817Y002",
        item_code1="010200000",
        cycle="D",
        sanity_min=-5.0,
        sanity_max=30.0,
        notes="Official ECOS market-rate series: 국고채(3년).",
    ),
    "ktb10y": ProviderMapping(
        instrument_id="ktb10y",
        provider="BOK ECOS",
        provider_symbol="817Y002:010210000",
        expected_unit="%",
        frequency="daily",
        source_url="https://ecos.bok.or.kr/api/",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="ktb10y",
        priority=PROVIDER_PRIORITIES["BOK ECOS"],
        stat_code="817Y002",
        item_code1="010210000",
        cycle="D",
        sanity_min=-5.0,
        sanity_max=30.0,
        notes="Official ECOS market-rate series: 국고채(10년).",
    ),
    "kofr_cd91d": ProviderMapping(
        instrument_id="kofr_cd91d",
        provider="BOK ECOS",
        provider_symbol="817Y002:010502000",
        expected_unit="%",
        frequency="daily",
        source_url="https://ecos.bok.or.kr/api/",
        direct=True,
        value_type="yield_percent",
        change_unit="bp",
        history_series_id="kofr_cd91d",
        priority=PROVIDER_PRIORITIES["BOK ECOS"],
        stat_code="817Y002",
        item_code1="010502000",
        cycle="D",
        sanity_min=-5.0,
        sanity_max=30.0,
        notes="CD(91일) is used for Phase 3A because the existing slot is KOFR or CD 91D.",
    ),
}


ALPHA_VANTAGE_SERIES = {
    "eurusd": ProviderMapping(
        instrument_id="eurusd",
        provider="Alpha Vantage",
        provider_symbol="EUR/USD",
        expected_unit="USD",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="fx",
        change_unit="%",
        history_series_id="eurusd",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        function="FX_DAILY",
        from_symbol="EUR",
        to_symbol="USD",
        sanity_min=0.01,
        sanity_max=10.0,
    ),
    "usdjpy": ProviderMapping(
        instrument_id="usdjpy",
        provider="Alpha Vantage",
        provider_symbol="USD/JPY",
        expected_unit="JPY",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="fx",
        change_unit="%",
        history_series_id="usdjpy",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        function="FX_DAILY",
        from_symbol="USD",
        to_symbol="JPY",
        sanity_min=1.0,
        sanity_max=1000.0,
    ),
    "usdcnh": ProviderMapping(
        instrument_id="usdcnh",
        provider="Alpha Vantage",
        provider_symbol="USD/CNH",
        expected_unit="CNH",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="fx",
        change_unit="%",
        history_series_id="usdcnh",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        function="FX_DAILY",
        from_symbol="USD",
        to_symbol="CNH",
        sanity_min=1.0,
        sanity_max=20.0,
    ),
    "usdkrw": ProviderMapping(
        instrument_id="usdkrw",
        provider="Alpha Vantage",
        provider_symbol="USD/KRW",
        expected_unit="KRW",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="fx",
        change_unit="%",
        history_series_id="usdkrw",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        function="FX_DAILY",
        from_symbol="USD",
        to_symbol="KRW",
        sanity_min=100.0,
        sanity_max=10000.0,
    ),
}


ALPHA_VANTAGE_PLACEHOLDER_SERIES = {
    "spx": ProviderMapping(
        instrument_id="spx",
        provider="Alpha Vantage",
        provider_symbol="SPX",
        expected_unit="index",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="index",
        change_unit="%",
        history_series_id="spx",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        enabled=False,
        function="INDEX_DATA",
        symbol="SPX",
        sanity_min=100.0,
        sanity_max=100000.0,
        notes="Disabled by default because Alpha Vantage INDEX_DATA is a Premium endpoint.",
    ),
    "ndx": ProviderMapping(
        instrument_id="ndx",
        provider="Alpha Vantage",
        provider_symbol="NDX",
        expected_unit="index",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="index",
        change_unit="%",
        history_series_id="ndx",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        enabled=False,
        function="INDEX_DATA",
        symbol="NDX",
        sanity_min=100.0,
        sanity_max=200000.0,
        notes="Disabled by default because Alpha Vantage INDEX_DATA is a Premium endpoint.",
    ),
    "kospi": ProviderMapping(
        instrument_id="kospi",
        provider="Alpha Vantage",
        provider_symbol="not enabled",
        expected_unit="index",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="index",
        change_unit="%",
        history_series_id="kospi",
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        enabled=False,
        notes="Left placeholder until official INDEX_CATALOG metadata confirms an actual KOSPI index symbol.",
    ),
    "kosdaq": ProviderMapping(
        instrument_id="kosdaq",
        provider="Alpha Vantage",
        provider_symbol="not enabled",
        expected_unit="index",
        frequency="daily",
        source_url="https://www.alphavantage.co/documentation/",
        direct=True,
        value_type="index",
        change_unit="%",
        history_series_id=None,
        priority=PROVIDER_PRIORITIES["Alpha Vantage"],
        enabled=False,
        notes="Left placeholder until official INDEX_CATALOG metadata confirms an actual KOSDAQ index symbol.",
    ),
}


COINGECKO_SERIES = {
    "btcusd": ProviderMapping(
        instrument_id="btcusd",
        provider="CoinGecko",
        provider_symbol="bitcoin",
        expected_unit="USD",
        frequency="daily",
        source_url="https://www.coingecko.com/en/coins/bitcoin",
        direct=True,
        value_type="crypto_price",
        change_unit="%",
        history_series_id="btcusd",
        priority=PROVIDER_PRIORITIES["CoinGecko"],
        coingecko_id="bitcoin",
        sanity_min=0.01,
        sanity_max=10000000.0,
        week_lag=7,
    ),
    "ethusd": ProviderMapping(
        instrument_id="ethusd",
        provider="CoinGecko",
        provider_symbol="ethereum",
        expected_unit="USD",
        frequency="daily",
        source_url="https://www.coingecko.com/en/coins/ethereum",
        direct=True,
        value_type="crypto_price",
        change_unit="%",
        history_series_id="ethusd",
        priority=PROVIDER_PRIORITIES["CoinGecko"],
        coingecko_id="ethereum",
        sanity_min=0.01,
        sanity_max=1000000.0,
        week_lag=7,
    ),
    "total_crypto_mcap": ProviderMapping(
        instrument_id="total_crypto_mcap",
        provider="CoinGecko",
        provider_symbol="/global.total_market_cap.usd",
        expected_unit="USD",
        frequency="intraday",
        source_url="https://docs.coingecko.com/reference/crypto-global",
        direct=True,
        value_type="crypto_market_cap",
        change_unit="%",
        history_series_id="total_crypto_mcap",
        priority=PROVIDER_PRIORITIES["CoinGecko"],
        sanity_min=0.01,
        sanity_max=1000000000000000.0,
        notes="Latest market cap only in Phase 3A; 1D/1W are left blank without a verified history endpoint.",
    ),
    "btc_dominance": ProviderMapping(
        instrument_id="btc_dominance",
        provider="CoinGecko",
        provider_symbol="/global.market_cap_percentage.btc",
        expected_unit="%",
        frequency="intraday",
        source_url="https://docs.coingecko.com/reference/crypto-global",
        direct=True,
        value_type="percentage",
        change_unit="pp",
        history_series_id="btc_dominance",
        priority=PROVIDER_PRIORITIES["CoinGecko"],
        sanity_min=0.0,
        sanity_max=100.0,
        notes="Latest dominance only in Phase 3A; 1D/1W are left blank without a verified history endpoint.",
    ),
}


DERIVED_SERIES = {
    "us2s10s": ProviderMapping(
        instrument_id="us2s10s",
        provider="Derived",
        provider_symbol="DGS10-DGS2",
        expected_unit="bp",
        frequency="daily",
        source_url="https://fred.stlouisfed.org/graph/?id=DGS10,DGS2",
        direct=False,
        value_type="yield_spread_bp",
        change_unit="bp",
        history_series_id="us2s10s",
        priority=PROVIDER_PRIORITIES["Derived"],
        notes="Calculated as UST 10Y yield minus UST 2Y yield, multiplied by 100.",
    ),
    "korea3s10s": ProviderMapping(
        instrument_id="korea3s10s",
        provider="Derived",
        provider_symbol="817Y002:010210000-817Y002:010200000",
        expected_unit="bp",
        frequency="daily",
        source_url="https://ecos.bok.or.kr/api/",
        direct=False,
        value_type="yield_spread_bp",
        change_unit="bp",
        history_series_id="korea3s10s",
        priority=PROVIDER_PRIORITIES["Derived"],
        notes="Calculated as KTB 10Y yield minus KTB 3Y yield, multiplied by 100.",
    ),
}


ALL_SOURCE_MAPPINGS = {
    **FRED_SERIES,
    **FRED_DISABLED_SERIES,
    **BOK_SERIES,
    **ALPHA_VANTAGE_SERIES,
    **ALPHA_VANTAGE_PLACEHOLDER_SERIES,
    **COINGECKO_SERIES,
    **DERIVED_SERIES,
}
